CREATE TABLE IF NOT EXISTS `hl_log` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ELEMENT_ID` INT NOT NULL,
  `USER_X` INT NULL,
  `FIELDS` TEXT NULL,
  `DATE_X` DATETIME NOT NULL,
  `VERSION` INT NOT NULL,
  `ENTITY_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ix_element_entity` (`ELEMENT_ID` DESC, `ENTITY_NAME` DESC));